### ISSUE TITLE
General category

### ISSUE THREAD

**Issue by zdroid** [philsturgeon/awesome-earth#125]
Some pages such as https://ourworldindata.org/ would fit all the categories. How are they supposed to be categorized? Perhaps a new, General category could serve this purpose.

**Comment by mbifulco** [comment]
This is a good idea - we're quickly running into taxonomical challenges like this.  It's a good problem to have, but we should come up with a solution for it!

**Comment by mbifulco** [comment]
This might mesh well with #123, too

**Comment by zdroid** [comment]
That sounds good. Wouldn't a category of "Miscellaneous", "Other" or "General" solve both problems?

**Comment by philsturgeon** [comment]
I've been trying to avoid a "Misc" category. We already kinda have a "catch all" which is sustainable living, and that's why we're slicing #106 out of there and trying to make things more correct. 

Things generally go in the closest category until we have enough to realize a new category. Then we have tags for grouping way more specific things or we'd have 10000 categories :D 

I think Carbon Reduction will become Footprint Calculators and Deforestation, and Sustainable Living might end up with a Food category once Clothing is split out, and we should find ourselves with fewer "General" things then. 

What do you think?

**Comment by zdroid** [comment]
That works, too. But then the question is, where would sites like the one above go?

**Comment by philsturgeon** [comment]
Wis this research? Do we start a research category, or are there already sites that cover that? Right now we aim at genera humans, consumers, business owners, local authorities, and soon finance people, etc. I dunno if we have much to tell scientists? I think they already know what’s up?

**Comment by zdroid** [comment]
This is the research data that should lead everyone into informed conclusions. :p

**Comment by philsturgeon** [comment]
Research isn’t for everyone but article summarising are. I looked again and this site does have that, so good, but there’s a lot of not-climate stuff on here. The first link looks relevant https://ourworldindata.org/food-choice-vs-eating-local but there’s loads of stuff about loneliness and aids and all sorts of other stuff.

Maybe we could use that first link in a new Food category?

**Comment by zdroid** [comment]
Yes, that'd be good.
