### ISSUE TITLE
SEO, Metadata, OpenGraph Images, etc

### ISSUE THREAD

**Issue by philsturgeon** [philsturgeon/awesome-earth#51]
We need to get [gatsby-plugin-react-helmet](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-helmet) involved so that we can add title, metadata, maybe it can help us reuse category images for the social shares and og stuff. I dont know what im talking about I think those are words.

```
  <Helmet
      title="The Gray Web Blog"
      meta={[
        { name: 'description', content: 'Sample' },
        { name: 'keywords', content: 'sample, something' },
      ]}
    />
```

More information over here: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-helmet

**Comment by philsturgeon** [comment]
@stephensamra if you've got the time for another one this would be a big help!

**Comment by stephensamra** [comment]
@philsturgeon sure thing!

**Comment by philsturgeon** [comment]
@stephensamra thanks for doing this, can you confirm if this is working on twitter? its not working for me but maybe the URLs are cached.

**Comment by stephensamra** [comment]
@philsturgeon I was using the [Twitter Card Validator](https://cards-dev.twitter.com/validator) to test it out and it seemed ok. It does seem to be taking the title and description from the meta tags and rendering them on the Twitter Card. There are no images set in the code yet so no image is appearing on the card right now. 

Trying to post a screenshot here but I think GitHub is having issues uploading images right now because of AWS issues 😅

Happy to take another look into the code if you're still experiencing issues.

**Comment by philsturgeon** [comment]
Thank you! Could you get the category images showing up when people tweet category pages? More images = more engagement. I tweeted a link and it was just the link, didn’t even show the description and a grey box, you know?

**Comment by stephensamra** [comment]
@philsturgeon yep, no problem. I'll use a real Twitter account this time to make sure it's showing correctly 👍
