### ISSUE TITLE
Missing actual economic issues

### ISSUE THREAD

**Issue by zdroid** [philsturgeon/awesome-earth#77]
I understood the point of the repository and I support its goal. But it is clearly missing (at least) 2 most important economic issues, which have way more impact on life of majority of the people than any of the mentioned in the list. Those are:
1. economic inequality
2. lack of industry regulation

The first makes all the issues mentioned in the repository more felt by those at the bottom than by those at the top. Some studies about this: [1](https://www.pnas.org/content/116/20/9808), [2](https://earth.stanford.edu/news/climate-change-has-worsened-global-economic-inequality#gs.inka7s), [3](https://www.un.org/esa/desa/papers/2017/wp152_2017.pdf). There are also letters and follow-up letters on the 1st one.

The second one is made clear when you check the data for energy and resources usage, for example in [EIA](https://www.eia.gov/outlooks/ieo/pdf/industrial.pdf)'s report. Industry uses 40% of total energy in OECD and 60% in non-OECD countries. The second most common use is for transportation (I can't find data for this), which is again connected to the first.

If you want to make an actual impact on the world, this repository must have those two issues mentioned at the top.

**Comment by philsturgeon** [comment]
Hey @zdroid, thank you for the suggestions! I understand that environmental and economic issues are heavily linked, and that has not been ignored in this project. The climate crisis is not the only problem in the world, but it is the one this project is focusing on. That does not mean we don't care about economic issues, as I said they are linked. The climate crises [disproportionate impacts to those living in poverty](https://www.theguardian.com/environment/2014/mar/31/climate-change-poor-suffer-most-un-report), which is why we recommend charities like [Eden Reforestation Projects](https://edenprojects.org/) who help people living in poverty to use less fossil fuels and improve their quality of life. For this reason we do not have specific economic issues on this site, that would be another site, but we are providing resources to address climate action for those with economic instability. 

Industry regulation is an interesting one, and one that would fit very well in the Politics section I¡m sure. We mention Carbon Tax a few times, and that generally covers the same stuff. We also have https://www.ourchildrenstrust.org/ which is an organization with lawyers literally suing governments around the world to demand action, so I think that might cover that. If you have some links for petitions/legislation in any particular countries then that'd be great to add to the site!

**Comment by zdroid** [comment]
I was checking whether the lack of those two issues is general project's policy or just lack of the needed information on those. It's good to hear it's mostly the second, so I'll consider putting some relevant links for those in the near future.

**Comment by philsturgeon** [comment]
Please do, so long as they specifically relate to climate action. Thank you!
